### ISSUE TITLE
Standard LICENSE.md for panel repos

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/process#103]
When creating the `*-panel` repos, what LICENSE should we be using? Most of the code repos in the Solid project use the MIT license. The spec-type repos and the more informal -panel repos probably need something different, like a Creative Commons license or the general W3C license?

**Comment by csarven** [comment]
INAL. Not sure if/how the "general" W3C license can be applied and be binding. MIT, or preferably CC0 or CC BY (to the "Solid community"?) is appealing and may be easier to transition the output of the panels where they can be potentially adopted by W3C/IETF/..

**Comment by timbl** [comment]
I feel it is important for the licence everywhere to be MIT.   Because there is no clear distinction between specs and code.  Specs have example code in them, and they also have test cases and algorithms and lookup tables and ontologies which people  will use as code, and want to merge with other MIT licence stuff.  So please keep everything MIT.

**Comment by Mitzi-Laszlo** [comment]
sorted https://github.com/solid/information/blob/master/license.md
