### ISSUE TITLE
Unclear which editorial assignment would review proposals from some panels

### ISSUE THREAD

**Issue by Mitzi-Laszlo** [solid/process#149]
There are several panels without editorial assignments including: 

* accessibility 
* artificial intelligence
* caching
* explaining the vision
* external interoperability and outreach
* internationalisation 
* privacy and individuals rights protection
* self hosting
* specification entry document 

This means it's unclear which editors would review proposals coming out of these panels. 

I propose staring editorial assignments that match these panels or defining which existing editorial assignments would review proposals coming out fo these panels.

**Comment by kjetilk** [comment]
Right! I would certainly review for the panels that I'm on. Do we need to put down the editors now, or could we defer it to when we see that actual work gets underway?

**Comment by Mitzi-Laszlo** [comment]
@kjetilk Great! 

Are there any more thoughts/feedback/ feelings about submitting a pull request to editors.md with these editorial assignments? 

How about we wait until the editorial assignments are up and then people can submit applications to those editorial assignments?

**Comment by Mitzi-Laszlo** [comment]
https://github.com/solid/process/pull/160

**Comment by kjetilk** [comment]
> @kjetilk Great!
> 
> Are there any more thoughts/feedback/ feelings about submitting a pull request to editors.md with these editorial assignments?
> 
> How about we wait until the editorial assignments are up and then people can submit applications to those editorial assignments?

I'm not quite sure what you mean. :-) Are you suggesting that panels suggest themselves to editorial assignments? 

I was thinking that panels form first, since they are the easy things to establish, and then, we/you need to figure out editorial review once we see if the panel will produce something to review. 

Since panels are easy to set up, I would expect some of them to not be able to produce anything, and so, I'm thinking we don't need to assign editors before we see if they actually do.
