### ISSUE TITLE
Wording of 'Implementers' section seems strange to me

### ISSUE THREAD

**Issue by pmcb55** [solid/process#184]
The Implementers paragraph reads very weirdly to me: https://github.com/solid/process#implementers. Being open-source and standardized, can't anyone (e.g. individuals or a loose group of friends, and not just 'companies or organizations') choose to implement any part (or all!) of Solid. Also, why explicitly list out 'Identity Provider, Pod Provider, and Application Provider' in the 2nd sentence - i.e. why just those 3, and where are they defined (not in this document anyway)? And the wording of that 2nd sentence seems strange too - i.e. those 3 things sound like 'parts of' a Solid implementation or eco-system, so how can a 'Solid Implementer' be any combination of those 'parts'? Do you mean an Implementer can choose to implement any 'part' of Solid (but if so, isn't that kinda redundant, given the specs are all open-source anyway)...?

**Comment by RubenVerborgh** [comment]
The section is indeed not factually accurate. Perhaps it can just be removed? It does not seem to serve a purpose for the process.

**Comment by kjetilk** [comment]
I agree it is awkward, but the background is to understand this requirement:
> Any proposal must be realistic and reasonable to implement, preferably with example implementations, and demonstrable support from Implementers.

What we're trying to avoid there is specifications ending up as purely theoretical exercises. There is no use to a spec if no-one is prepared to implement it. The idea is therefore that those proposing a feature to be specified should ensure that they have some support from implementers. Implementers can be anyone, but the realization is that there are some groups that you'd have to find support from to actually, practically have an impact.

It could be argued that it is sufficient to say that, but then, the question "who is that I would need to have demonstratable support from?" isn't answered in the process document. The purpose of Implementers section is to answer that question. 

A text to answer that question better is welcome, though.

**Comment by csarven** [comment]
Right, I think the wording can be improved because it comes across like stakeholders but that wasn't the intention (IMO). The text may have partly emerged out of discussion I had with Justin prior to drafting. The intention was basically what Kjetil describes above. It ties into progressing specs in that there are implementations for each interop feature. Implementers are part of the spec process in that sense - without them and (experimental) implementations, there is no realistic or mature spec. From the perspective of the spec, their role will be more apparent and important when the spec reaches the Candidate Recommendation state. See also https://www.w3.org/2019/Process-20190301/#implementation-experience

**Comment by justinwb** [comment]
Yes the wording can be improved a bit but @kjetilk and @csarven have it right. We needed to point out that there is a group of stakeholders that have implemented (in various manifestations) pieces of the solid specification, and proposals to change or extend the specification should include communication and (ideally) support from this group of stakeholders.

**Comment by Mitzi-Laszlo** [comment]
Sounds good, submit a pull request with a specific way to improve the copy if still needed.
