### ISSUE TITLE
The effect of non-diclosure agreements on developers

### ISSUE THREAD

**Issue by sideshowtom** [solid/process#204]
This issue was prompted by discussion in another issue:

https://github.com/solid/process/issues/202#issuecomment-630158221 .

These are some examples I can think of where the decision making of developers "in the wild" is adversely affected by the effect of non disclosure agreements.

Nobody from the forum, afaict, is working on solid-panes.  The mashlib has been in a state that has been described as a proof of concept, and clunky.  Though I cannot document it, I believe developers have been expecting it to be improved substantially for some time, but it hasn't happened.  This is a cause of confusion that is relevant to non-disclosure agreements.  Is it being improved for private customers?  We don't know.

Another similar example is in the area of data interoperability.  Again I can't prove it, but I believe developers on the forum are hanging back and expecting others to lead in this area.  If they had more information, especially about what is *not* getting attention, they would probably be more inclined to pitch in.

**Comment by csarven** [comment]
>Nobody from the forum, afaict, is working on solid-panes. The mashlib has been in a state that has been described as a proof of concept, and clunky.

If so, I'm sure everyone can benefit from your contributions to those projects.

**Comment by sideshowtom** [comment]
I thought I was being constructive, but it turns out I'm just a process problem.

**Comment by csarven** [comment]
I fail to see how (your perceived) lack of activity or quality in those projects is process related. I don't know why you can't turn that around into something useful to all. Clearly you deeply care about those repositories/projects as you've brought them up. You can reach out to folks that have worked on them to get you going. Would you like introductions?

**Comment by sideshowtom** [comment]
Now its you that's off topic.  It isn't just me that is hanging back, and I think the topic of the issue is one of the reasons.  It seems to me that issue can be addressed on its own merits.

**Comment by justinwb** [comment]
@sideshowtom The scope of the Solid project is to evolve the ecosystem of [Solid specifications](https://github.com/solid/specification) so that they can be used by anyone freely in the public or private space. We operate under the [Solid Process](https://github.com/solid/process) in an open and transparent fashion. Minutes are filed on the [community group wiki](https://www.w3.org/community/solid/wiki/Meetings), or in the github repository for each panel. We cannot speak on behalf of any private company, and consequently it's inappropriate to file issues here targeting any individual organization. If you have a question or issue to raise with a private company, i suggest you take it up with them directly. 

Our top focus in the Solid project is to create specifications and standard patterns that can be used by everyone to create software. It's up to the community, which is made up of individuals, academia, and organizations from the public and private sector, to take these specifications and develop on them. We cannot control what any of them do - we can only do our best to improve the specifications so that all of you can do more with them, and support any implementation that aims to codify them as best we can.

> Nobody from the forum, afaict, is working on solid-panes. The mashlib has been in a state that has been described as a proof of concept, and clunky.

Any issues or concerns that you have around software like mashlib or solid-panes should be addressed in that specific software repository. We could certainly discuss how the work we're doing on the specifications influences software like mashlib or solid-panes - but your comment seems to be directed more at the user experience of those specific implementations, and so it should be directed to people working in those respective repositories so they can address your concerns properly.

> Another similar example is in the area of data interoperability.

Were you aware that there's a [data interoperability panel](https://github.com/solid/data-interoperability-panel) that [meets weekly](https://github.com/solid/data-interoperability-panel#meetings)? 

> If they had more information, especially about what is not getting attention, they would probably be more inclined to pitch in.

If you want more perspective on what we're focusing on in the interoperability panel, you can start by reading the [Problems and Goals](https://github.com/solid/data-interoperability-panel/blob/master/problems-and-goals.md) that are guiding our current work. 

All panel sessions are open to anyone that wants to join, and we do our work out in the open. If you'd like a run-through of current interoperability panel work items, join a session and we'll take you through them. 

I'm sure there are ways we can improve how we communicate what we're up to across the various panels to keep the community informed. If you have suggestions on how we can do that, we're always happy to listen. In fact, that is the type of feedback we were hoping to elicit in solid/process#202.

Circling back to the title of this specific issue, and content in the original post related to a private organization - it really doesn't belong here. I believe your aim is to be constructive, and in that light am respectfully requesting that you update the issue title and contents of the original post to remove any speculation about private companies, and instead refocus it on the issues and concerns that we can and should actually address in this venue. Otherwise this issue isn't constructive as reported.

**Comment by sideshowtom** [comment]
Ok, fair enough.  I've updated the title of the issue and edited the original comment accordingly.

**Comment by justinwb** [comment]
> Ok, fair enough. I've updated the title of the issue and edited the original comment accordingly. Some examples were requested, so I left those in.
> 
> I am aware of the interoperability panel and have been following the minutes.

Thank you. I think more accessible communication and interaction about the good work that's happening out in the open could go a long way towards addressing some of the concerns you report. Since you've been following the interoperability activity, I'd welcome any thoughts you have on how we could better communicate what we're up to so people feel more informed or even more inclined to participate.
