### ISSUE TITLE
Thoughts and Feedback on the current state of the repository

### ISSUE THREAD

**Issue by maxidorius** [solid/process#39]
I've wrote down my thoughts while reading the various documents of this repository.
First of all, thank you for putting this together! This is great work and I like how it identifies the roles and how one can contribute to the spec.

I have open questions that I believe can help complete the documents. There is no need to answer them directly here, but I feel those needs *some kind of* answer in the document themselves, or the documents should be updated so they answer them.

These thoughts and questions reflect my view of them as an outsider who only passively followed the project in the past and only start actively contributing in the last weeks.

---

#### Panels
- What about "official" panels that cover specific parts of the spec, like OIDC-WebID, to ensure
  1. It collects, aggregate and sends upstream the community issues
  2. The spec keeps on making sense over time (technology changes, etc).
- Is a panel an informal or a formal group of people?

If we put ourselves in the view of a person who just got to know about the Solid project and wants to contribute:
- What conditions makes it so I should be part of a panel?
- What is the incentive of being in a panel, or create one?
- Why can't I just talk to whoever is in charge of a spec section if I have questions about it?

#### Stakeholders
- The stakeholder listing doesn't have individuals we can reach. I don't think "Solid Community" is helpful to know who to reach to, or how. There should be one person of contact or one front person for any type of org.
- If consulting the stakeholders not mandatory in any process (as far as I can see), why should I care about them?
- Users are "individuals, companies, or organizations" while Implementers are "companies or organizations"
  1. Is not listing individuals for Implementers an omission? or an explict choice?
  2. If choice, why?

#### Drafting proposals
> Submit a pull request or issue on the Solid Specification repository in GitHub"

Shouldn't the link on "Solid Specification" link to the new repo?

> "Propose an item for the W3C Solid Community Group call"

How?

> "Any proposal must be realistic and reasonable to implement":

This is highly subjective, and not very useful. How should one judge if it is "realistic and reasonable to implement"? Is it a matter of considering all major programming languages? Or something else?

The vote proposal is good, but seems a bit out of place in the document.
Where should this take place? In a PR? In an issue? On Gitter?

#### Becoming an Editor
- Is the choice of accepting someone as an editor at the sole discretion of the director(s)?
- Are there already known specifics traits/facts to become one that the director will look for? e.g. what should I do before hand to maximise my chances to become one, if I wanted.
- What is the editor responsible for? What MUST they do? What SHOULD they do? What MAY they do? What they SHOULD NOT do? What they MUST NOT do?
- It seems relevant to also have the areas/realms that each editor is competent on, so outsiders know who to go talk to when drafting/presenting proposals.

#### Overall
It's all very abstract, and the process lacks the concept of "Point of contact". As an outsider contributor, the first and possibly only thing I worry about is who can I reach to for a specific topic, even if that person redirects me to someone else/

Reading the various documents, it feels like Solid is some unreachable entity that is not really human. I think we should humanize the documents a bit more, without changing the process itself.

**Comment by dmitrizagidulin** [comment]
@maxidorius You bring up some excellent points. I think these are all just docs clarifications, without major changes to the process.

**Comment by Mitzi-Laszlo** [comment]
Thank you @maxidorius for these points. The final outcome of the conversations that went into writing the culture repository are all public. As Solid Manager I have been moderating many of these conversations or part of them so perhaps it helps for me to try and give an overview of the perspectives and thinking that went into the final output. 

# Panels 
Panels are deliberately fluid and voluntary with next to no review process. Although the administrator or Solid Manager has to merge the pull request there is no real requirement. The reason being is to incentivise conversations around Solid and have a way for us to tell each other about what we are interested in, what we are working on, and where we are working on those themes. There are no obligations around starting or stoping a panel, it is a very informal structure. 

# Stakeholders
There were those who did not want to list the individuals on the Solid Community because it is unwieldy. There were others who wanted the stakeholders (rather than the editors) to have the final vote. Knowing who can vote is essential to understand what the outcome it. The compromise was to voluntarily list the stakeholders so that a consultative vote is possible but not binding. 

# Drafting proposals

The location of the Solid specification is in flux because it is being developed. The conversation on gitter today raised this concern and the solution was to make sure that all the Solid spec related repos link to each other in the readme. 

The W3C Solid Community Group call is openly explained on [the wiki](https://www.w3.org/community/solid/wiki/Meetings) and I am on the look out as Solid Manager for people who are wanting to raise something and would like me to add an item for them. 

There are multiple subjective criteria in the process. The element of "realistic" was in response to some concerns about creating theoretical solutions. There is certainly room for improvement in the process to get more measurable that we will likely have to tackle in the future. However for now it is important to keep the concepts listed in mind and use them not in a legalistic sense but in spirit and culture when working together. 

Votes need to happen in public and all editors should be aware of it, the place is not defined beyond that. 

# Becoming an Editor

Process and appointment to become an editor is deliberately left to the discretion of the director who started the project. Editors responsibilities are listed in the process. There is a degree of self management for now, with multiple checks and balances such as that the director can intervene with a veto at any point. 

# Overall

On https://www.solidproject.org there is an email that leads to me as Solid Manager. I am available as a point of contact. There are many others who are actively chipping in too and it's very helpful when they list themselves on Panels for example so that they can be found. 

Again, it's really useful for you to raise these points because if you have them it is likely others have and will too. Hopefully my response fills in some of the gaps. 

If anyone feels that I misrepresented any element or should add more back story please do feel free to add that. Happy to give a shot at answering any more questions if there are too.
