### ISSUE TITLE
Definition of substantive changes in the editorial process might cause trouble

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/process#57]
The current process says:

1. Proposals for substantive changes to the Solid Specification, Solid Roadmap, or Supporting Documentation go through an editorial review process.

2. A change is considered substantive when it alters the normative text of the Solid Specification or the Solid Roadmap.

3. Candidate proposals to the Solid Specification, Solid Roadmap, or Supporting Documentation submitted for review go through an editorial process before they are accepted.

4. Candidate proposals and the results of any vote related to the same need to be put forward to the editors for review.

I wanted to note the following issues that can arise from a strict interpretation of the above:

a. Typos in a normative section are currently considered "substantive" and need to go through an editorial process.

b. 3 seems to obsolete 2, in the sense that it does restrict itself to substantive changes.

c. (minor) It's also unclear whether the actual merging has to happen by an editor or not, and whether this depends on the change being substantive.

We might want additional clarity there. We can probably not expect 3 editors to chime in for every minor detail. Especially given the current lack of editors (none appointed yet, only 4 open applications so far), PRs such as https://github.com/solid/specification/pull/13 are currently in limbo.

A more liberal interpretation of the process could be appropriate, but it is unclear to what extent this is desired, so actual changes might be needed.

(Just tagging a problem from the field here, I unfortunately cannot contribute to a solution.)

**Comment by acoburn** [comment]
Ultimately, the question of substantive vs. non-substantive will be a judgement call by the editors, and it may be helpful if this process document allows that level of flexibility. @RubenVerborgh is correct that there could be non-substantive changes to normative text.

In fact, here is one such example of a non-substantive change to normative text in the [W3C Web Annotation](https://github.com/w3c/web-annotation/pull/414) repository.

I liked the way that WG handled these cases, where an issue or PR would be explicitly flagged as non-substantive" by an editor.

**Comment by justinwb** [comment]
Thanks for flagging this and breaking down the problem cleanly @RubenVerborgh. I agree with the issues as you listed them, and with the suggestion that we need additional clarity. I'll take a crack at working up some language this weekend.

**Comment by justinwb** [comment]
@RubenVerborgh Would [these changes](https://github.com/solid/culture/commit/df05c4ce46ae71d6f64649a8aefb765dce3d50d6) or something close to them address the points that you raised? Inline comments directly on that commit are more than welcome. After we've established better language that clears up any ambiguity we can figure out if the end result is substantive and requires another approval by @timbl.

**Comment by Mitzi-Laszlo** [comment]
(@justinwb the link to the suggested changes is broken)

**Comment by justinwb** [comment]
> (@justinwb the link to the suggested changes is broken)

The link is good - github has been having issues and you likely ran into them.

**Comment by Mitzi-Laszlo** [comment]
If editors explicitly make the final decision about if a change is substantive then we would need to detail what happens when two editors disagree. A possible solution is to state that there needs to be a unanimous decision from all editors. If there are any disagreements the judgement is made by the Solid Director. However...before getting into the nitty gritty of strict interpretations etc.. 

There's another factor here....

Fiddling around with non-substantive changes to the process and debating about if a change is substantive or not could be really unproductive. 

Let's take 10 steps back and think about why we are doing this. 

The purpose of this agreement on how to agree is to be able to move forward as a team for now. There's no way you can make everyone happy with a process and I'm really impressed with the collaborative effort to write this agreement together in a way that everyone compromised and we delivered a final result.

There is a point when you need to draw a line underneath it for now and agree to pick it up in some months, years, or when there is a real substantive ( :) ) gridlock block. 

For this reason I prefer @acoburn suggestion of allowing for level of flexibility and working with what we have now.

The process is there to help us work together. The sprit and culture of how we use this process when we work together is also important. We need to remember we are team and we need to support each other and use it to progress our collective mission, vision, and values.

**Comment by justinwb** [comment]
> If editors explicitly make the final decision about if a change is substantive then we would need to detail what happens when two editors disagree. A possible solution is to state that there needs to be a unanimous decision from all editors. If there are any disagreements the judgement is made by the Solid Director.

If there's disagreement, then I think it is better for it to automatically default to substantive, which we've got existing process for. I reflected that [in this new commit](https://github.com/solid/culture/commit/d43a76d5b928825787e4d31655feb40cff068a63).

> There is a point when you need to draw a line underneath it for now and agree to pick it up in some months, years, or when there is a real substantive ( :) ) gridlock block.

Completely agree, although I don't think that time is now. A brand new process is like a brand new piece of software that no one has used yet. We design both with the best of intentions, but once you put it out there and have others attempting to use it, they alert you to all kinds of problems, gaps, bugs, or logical issues that exist within it. If we don't take advantage of feedback as it comes in, especially in these early days, we lose valuable opportunities to improve the process and get to that mature state. We also run the risk of alienating contributors who raise valid issues with the process as it stands.

**Comment by Mitzi-Laszlo** [comment]
@justinwb [this new commit](https://github.com/solid/culture/commit/d43a76d5b928825787e4d31655feb40cff068a63) is a good solution. 

[Here's another issue about the offshoot conversation.](https://github.com/solid/culture/issues/74)

**Comment by kjetilk** [comment]
Just a short note on 
> A change is considered substantive when it alters the normative text of the Solid Specification or the Solid Roadmap.

I think the intention was to capture changes that influences behaviour, and so just saying "normative text" was a bit unfortunate. We could say something like "alters the semantics of the normative text"? So, grammar changes could also be considered non-substantiative?

**Comment by TallTed** [comment]
> "alters the semantics of the normative text"

and/or something like "changes that would require revision of an existing implementation of the old text in order for that implementation to comply with the new text" are substantive.

**Comment by justinwb** [comment]
Please see #95 for a proposed resolution to the items raised in this issue.

**Comment by RubenVerborgh** [comment]
Absolutely, thanks again.
